module.exports=userData=[
    {
        id:1,
        firstname:"Pedro",
        lastname:"Gonzales",
        email:"master@gmail.com",
        birthDate: "1992-07-27",
        address:{
            id:1,
            street:"13",
            city:"Lima",
            country:"PE",
            postalcode:"42030"
        }
    },
    {
        id:2,
        firstname:"Giancarlo",
        lastname:"Guizado",
        email:"lapepa@gmail.com",
        birthDate:"1996-11-06",
        address:{
            id:2,
            street:"20",
            city:"Trujillo",
            country:"PE",
            postalcode:"42050"
        }
    }
]